# Generated by Django 2.2 on 2022-07-28 18:15

from django.db import migrations, models
import django.db.models.deletion
import main_page.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_at'], 'verbose_name_plural': 'Experience'},
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='companies/', validators=[main_page.validators.validate_logo]),
        ),
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience', to='main_page.Skill', verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='experience',
            name='technologies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience', to='main_page.Technology', verbose_name='Technologies'),
        ),
    ]
