# Generated by Django 2.2 on 2022-08-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technology',
            new_name='Instrument',
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['-value']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-value']},
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=24),
        ),
    ]
