# Generated by Django 2.2 on 2022-08-08 19:38

import django.utils.timezone
import main_page.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20220808_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.AddField(
            model_name='company',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(upload_to='public/', validators=[main_page.validators.validate_logo]),
        ),
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(validators=[main_page.validators.validate_github]),
        ),
    ]
