# Generated by Django 2.2 on 2022-08-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20220808_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-employment_type', '-start_at'], 'verbose_name_plural': 'Experience'},
        ),
    ]
