name: CI

on:
  push:
    branches: [ "master" ]

jobs:

  tests:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup python
        
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
  
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r requirements.txt

      - name: run flake8
        run:
          python -m flake8
